name: Update Index
on:
  push:
    paths:
      - 'notices/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v1.x
        - name: Update index.md
          run: |
            deno run --allow-read --allow-write scripts/update_index.ts
        - name: Commit changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add index.md
            git commit -m "Update index" || echo "No changes to commit"
            git push
  